### ISSUE TITLE
Save a term

### ISSUE THREAD

**Issue by marcelvillerius** [codemonauts/craft-glossary#8] opened 2022-11-04 07:24 UTC
Thanks for this great plugin! I discovered a small issue:

If you want to use COMMAND + S to save a **term**, it is not working as expected and if you click on 'Save and continue editing', the term will close, so it behaves different from regular entries.

Best!

Marcel

**Comment by kringkaste** [comment] 2022-12-14 16:41
Hi Marcel! I cannot reproduce this. Both is working as expected. What version of the plugin do you use?

**Comment by marcelvillerius** [comment] 2022-12-15 10:27
Thank you for the reply, Tom. I forgot to mention that I work with version 1.0.5 on Craft 3. Maybe I should upgrade to Craft 4 first

**Comment by kringkaste** [comment] 2022-12-15 10:28
Ok, I will release a new version for Craft 3 today. So I will check this.

**Comment by marcelvillerius** [comment] 2022-12-15 10:30
Great, thanks!

**Comment by kringkaste** [comment] 2022-12-16 12:50
Fixed in release 1.0.6. Thanks for reporting it.

**Closed as completed by kringkaste** 2022-12-16 12:50 UTC
